name: rte-benchmarks
channels:
  - rttools
  - conda-forge
dependencies:
  - python>=3.12
  - numpy
  - scipy
  - xarray
  - netcdf4
  - libnetcdf<4.10
  - pyarts>=2.6.16
  - pip
  - pip:
        # PyPI/egg name is fluxsimulator, not pyarts-fluxes
        - "fluxsimulator @ git+https://github.com/atmtools/pyarts-fluxes.git@main"
